// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-bjxMAdcaCXsUjMIVXUI1yNLV1ZJdNKE',
    appId: '1:46958918166:web:04cbc32732c7e0671dd337',
    messagingSenderId: '46958918166',
    projectId: 'chatapptest-faf25',
    authDomain: 'chatapptest-faf25.firebaseapp.com',
    storageBucket: 'chatapptest-faf25.appspot.com',
    measurementId: 'G-3B6DGE888N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdnNX1_8SKVi9j0Op59_39CiiV4m6DMuI',
    appId: '1:46958918166:android:4e60574d080a54721dd337',
    messagingSenderId: '46958918166',
    projectId: 'chatapptest-faf25',
    storageBucket: 'chatapptest-faf25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2HxL7nDVa2FNwB01YVGihSz3BqEwl0jI',
    appId: '1:46958918166:ios:a34794d0677177d21dd337',
    messagingSenderId: '46958918166',
    projectId: 'chatapptest-faf25',
    storageBucket: 'chatapptest-faf25.appspot.com',
    iosBundleId: 'com.example.chatAppTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2HxL7nDVa2FNwB01YVGihSz3BqEwl0jI',
    appId: '1:46958918166:ios:4707d4a4c27b4f761dd337',
    messagingSenderId: '46958918166',
    projectId: 'chatapptest-faf25',
    storageBucket: 'chatapptest-faf25.appspot.com',
    iosBundleId: 'com.example.chatAppTest.RunnerTests',
  );
}
